title: ÅBIM
description: OpenBIM Web application for 4D and 5D Project Management
baseurl: "/ABIM-SHOWCASE"
url: "https://riccardopadoan28.github.io"

# Minimal Mistakes Theme
remote_theme: mmistakes/minimal-mistakes@4.26.2
minimal_mistakes_skin: "contrast"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: Riccardo Padoan
  avatar: "/assets/images/profile.jpg"
  bio: "BIM & Construction Technology Specialist"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/riccardopadoan28"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/riccardopadoan00/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/riccardopadoan28"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/riccardopadoan00/"

locale: "en-US"
timezone: "Europe/Rome"