title: ÅBIM - OpenBIM Web Application
description: 4D/5D Automation Platform for Project Management
baseurl: "/ABIM-SHOWCASE"
url: "https://riccardopadoan28.github.io"

theme: jekyll-theme-cayman

plugins:
  - jekyll-feed
  - jekyll-seo-tag

author: Riccardo Padoan
github_username: riccardopadoan28

# Custom
social:
  - platform: GitHub
    url: https://github.com/riccardopadoan28/ABIM-SHOWCASE
  - platform: LinkedIn
    url: https://www.linkedin.com/in/riccardopadoan00/